from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import tensorflow as tf

from backend.core.config import get_predictions_path

LOGGER = logging.getLogger(__name__)

SRC_ROOT: Path = Path(__file__).resolve().parents[1]
TRAINED_MODELS_DIR: Path = SRC_ROOT / "results" / "trained_models"


@dataclass(frozen=True)
class SequenceModelArtifacts:
    """Container for pre-trained sequence models used in inference.

    Attributes:
        lstm_model: Pre-trained LSTM model loaded from disk.
        gru_model: Pre-trained GRU model loaded from disk.
    """

    lstm_model: tf.keras.Model
    gru_model: tf.keras.Model


# Hold the prepared prediction table used by the website/backend route lookup.
class PredictionArtifacts:
    """Container for prepared prediction rows loaded from CSV artifacts.

    Attributes:
        predictions: Prediction table containing datetime, location, and output columns.
    """

    def __init__(self, predictions: pd.DataFrame):
        """Create an in-memory holder for prepared prediction rows.

        Args:
            predictions: Loaded predictions dataframe.
        """
        self.predictions = predictions


def load_keras_model(model_path: str | Path) -> tf.keras.Model:
    """Load a pre-trained Keras model from a .keras artifact.

    Args:
        model_path: File system path to the model artifact.

    Returns:
        The deserialized TensorFlow Keras model.

    Raises:
        FileNotFoundError: If the artifact does not exist.
    """
    resolved_path = Path(model_path)
    if not resolved_path.exists():
        raise FileNotFoundError(f"Model artifact not found: {resolved_path}")

    LOGGER.info("Loading Keras model artifact from %s", resolved_path)
    return tf.keras.models.load_model(str(resolved_path))


def load_sequence_model_artifacts(model_dir: str | Path = TRAINED_MODELS_DIR) -> SequenceModelArtifacts:
    """Load pre-trained LSTM and GRU models from the trained-models directory.

    Args:
        model_dir: Directory containing .keras sequence model artifacts.

    Returns:
        SequenceModelArtifacts with loaded LSTM and GRU models.
    """
    model_root = Path(model_dir)
    lstm_path = model_root / "lstm_model.keras"
    gru_path = model_root / "gru_model.keras"
    return SequenceModelArtifacts(
        lstm_model=load_keras_model(lstm_path),
        gru_model=load_keras_model(gru_path),
    )


# Load the prepared predictions CSV generated by src.predict.
def load_prediction_artifacts(
    predictions_path: str | Path | None = None,
    data_key: str = "2014",
) -> PredictionArtifacts:
    """Load prepared prediction CSV artifacts used by routing APIs.

    Args:
        predictions_path: Optional explicit path to predictions CSV.
        data_key: Dataset key used to resolve default artifact path.

    Returns:
        PredictionArtifacts containing normalized and sorted prediction rows.
    """
    if predictions_path is None:
        predictions_path = get_predictions_path(data_key)
    LOGGER.info("Loading prepared prediction artifact from %s", predictions_path)
    predictions = pd.read_csv(predictions_path, parse_dates=["datetime"])
    predictions = predictions.sort_values(["datetime", "scats_number", "location"]).reset_index(drop=True)
    return PredictionArtifacts(predictions=predictions)
